### ISSUE TITLE
Query.hasNext() will re-do the query?

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#12]
It seems that if we iterate through all the answers of a Query, then `Query.hasNext()` will yield false, as expected.

However, on a second call too `Query.hasNext()`, the query will be re-opened and the solutions enumerated again. Is that what we want? Wouldn't it better to explicitly require to re-open it before `hasNext()` returns true again?

**Comment by anionic** [comment]
(and, hopefully, `Query.next()` will throw an exception, as required by Java's Iterator interface, which is what is being implemented here)
What happens after that is undefined; apparently the designers of the Collections Framework deliberately kept this interface minimal, not to burden implementors unnecessarily (some iterables cannot be reset).
We definitely don't want to have to "open"  the Query explicitly before its first use; that would be redundant and unidiomatic.
Current behaviour is not by design AFAIK (I guess it just drops out of Query having only two states: closed or open), nor documented AFAIK; it can only be an issue for user code which strays into undefined areas (calling next() or hasNext() beyond end-of-iteration).
If we change anything, I reckon it should be to ensure that each Query instance can only be used once (users may wrongly but understandably assume that next() and hasNext() will continue to signal end-of-iteration).
Alternatively, I could document (and guarantee) the present behaviour?

**Comment by ssardina** [comment]
Thanks anionic. I understand now the background regarding Iterators/Collections a bit more.

First, yes `Query.next()` throws exception if we got to the end. So that is good now.

From what you said I would tend to prefer that `hasNext()` keep saying `false` so that we mimic more closely SWI/Prolog behavior: when you get to the end of all solutions Prolog says no or false, it does not re-start the answers. So I would vote for your first solution: "Query instance can only be used once".

Indeed we do not want to ask the user to explicitly open the query. This should happen automatically in the first use.

**Comment by ssardina** [comment]
Now that I have investigated JPL a bit more, I propose the following changes:

1. Make `.hasNext()` (and all its relatives like `hasMoreSoltions()`) do not re-open the query once it is exhausted. 
2. Introduce `reset()` that resets the query if one wants, so that solutions can be retrieved again.
3. Make `.nextSolution()` (and all its relatives like `next()`) do advance the iterator if possible, that is, they automatically call `hasNext()` and yield the next bindings. That is more compatible with Java iterators right?

What do you think @anionic ?

**Comment by ssardina** [comment]
I went ahead and did it both in my fork, and aligned the iterator behavior to the standard in Java:

https://github.com/ssardina-research/packages-jpl/issues/3

@JanWielemaker , @anionic are you happy that I propose a pull request for that to the main repo?

**Comment by anionic** [comment]
1. OK; the "cycling" behaviour was undocumented and unexpected, but we should warn users (where, when?) of this change
2. OK, although this is outside the Iterator spec ; presumably it can be called in any state
3. OK, this fixes the contract breach that next() didn't advance, preserving laziness

**Comment by ssardina** [comment]
Thanks @anionic . Well to move this forward I went ahead and issued a pull request #16 so we can discuss there if there are issues.

yes `reset()` can be called in any state and is outside the iterator spec (we already have other methods that go beyond the Java spec fo iterators)

**Comment by ssardina** [comment]
This has been resolved in PR #16
