### ISSUE TITLE
Provide Solution class to represent goal solutions

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/packages-jpl#50]
So far a solution (given by queries) is a `Map<String, Term>`

It would be nice to provide a more abstract `Solution` class that makes that representation transparent.

The class will have methods to access things like the bindings or whether it is empty.

Minor technically but meaningful for the programmer, to relieve from using Mappings all the time.

**Comment by anionic** [comment]
What JPL calls a "solution" (and has done since Fred Dushin's v1.0.1 of 1998 or thereabouts) is more pedantically a "substitution", i.e. a map from (named) variables in a goal to terms, resulting from a successful proof (or exit from a call). Fred's code represented this with a HashTable, but JPL7 uses the newer and preferred java.util.Map interface from the Collections Framework; each Entry is a binding of a variable. (A "solution" strictly refers to the original goal with its variables bound, which is not what JPL returns.)

Can you illustrate how your proposed Solution class would be usefully more abstract than the Map interface, and how it would be "transparent"?

How can a Solution be "empty"?

I guess if your Solution class implements java.util.Map then existing user code would be supported, but it is not clear to me what you would be adding to Map.

PS if Joshua Bloch advocates your approach then you have my support!

**Comment by ssardina** [comment]
I emailed Joshua. Will let you know when he comes back ;-)

You are right in everything you said, and if we think a further abstraction won't add much, we don't need it.  Great to have your opinion. "Substitution" could be a good name too.

Thinking about it a bit more, and as you suggested, this new class won't add much beyond Map, which an be indeed interpreted as a a "substitution". If I do it, I would have things like `Solution.getBinding("x")` which would be the same as what `Map` exposes already.

I guess the best is to explain this a bit more explicitly in the doc and that's it, but I checked and it is actually there pretty clear in **"Querying Prolog"** section.

So, all good, no need to do anything here, thanks for commenting.
